spring.application.name=backend

# 1. SUPABASE (POSTGRESQL) VERİTABANI BAĞLANTISI
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.taholfwkjymyuvflxpnr
spring.datasource.password=zFiUB272qh671NYI
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 2. HIBERNATE / JPA AYARLARI
# ===============================
# DİKKAT: Tabloları SQL dosyasıyla kendimiz oluşturduğumuz için burası kesinlikle 'none' veya 'validate' olmalı. 
# 'update' yaparsak Spring kendi kafasına göre tabloları değiştirmeye çalışır ve mimarimiz bozulur.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 3. REDIS (ÖNBELLEK VE SEPET) AYARLARI
# ===============================
# Docker üzerinde standart portta (6379) çalıştığı için bu varsayılan ayarlar yeterlidir.
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# 4. UYGULAMA PORTU
# ===============================
server.port=8080
